config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/queues'

  mount Ddr::API::Root => Ddr::API.path

  mount Blacklight::Engine => '/'
  root to: 'catalog#index'
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  if Rails.env.production?
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  else
    devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
  end

  get 'id/*permanent_id', to: 'ddr/permanent_ids#show'

  get 'admin/api'
  get 'admin/expire_public_rails_cache'
  get 'admin/queues'

  def id_constraint
    /\h{8}-\h{4}-\h{4}-\h{4}-\h{12}/
  end

  def content_routes
    get 'upload'
    patch 'upload'
    get 'files'
  end

  def event_routes
    get 'events'
    get 'events/:event_id', action: :event
  end

  def publication_routes
    Ddr::V3::PublicationService.workflow_event_names.each do |event|
      get event
    end
  end

  def roles_routes
    get 'roles'
    patch 'roles'
  end

  def structure_routes
    get 'generate_structure'
    get 'structural_metadata'
  end

  def iiif_routes
    get 'iiif'
    get 'generate_iiif'
  end

  def amd_routes
    get 'admin_metadata'
    patch 'admin_metadata'
  end

  def index_doc_routes
    get 'index_doc'
  end

  def repository_routes
    event_routes
    roles_routes
    amd_routes
    index_doc_routes
  end

  def repository_contraints
    { id: id_constraint }
  end

  def no_repository_routes_for(_name)
    %i[index destroy]
  end

  def repository_options(name)
    { except: no_repository_routes_for(name),
      constraints: repository_contraints }
  end

  namespace :ddr do
    scope 'superuser', as: 'superuser' do
      get 'sign_in', to: 'superuser#create'
      get 'sign_out', to: 'superuser#destroy'
    end

    def repository_resource(name)
      resources name, repository_options(name) do
        member do
          repository_routes
          yield if block_given?
        end
      end
    end

    def repository_content_resource(name)
      repository_resource name do
        content_routes
      end
    end

    repository_resource :collections do
      content_routes
      publication_routes
      structure_routes
      iiif_routes
      get 'collection_info'
      get 'items'
      get 'attachments'
      get 'targets'
      get 'export'
      post 'export'
      get 'aspace'
      post 'aspace'
    end

    repository_resource :items do
      content_routes
      publication_routes
      structure_routes
      iiif_routes
      get 'components'
    end

    repository_resource :components do
      content_routes
      publication_routes
      get 'intermediate'
      get 'stream'
      get 'captions'
    end

    repository_content_resource :attachments

    repository_content_resource :targets

    resources :batches, only: %i[index show destroy] do
      member do
        get 'procezz'
        get 'retry'
        post 'retry'
        get 'validate'
      end
    end

    get 'my_batches' => 'batches#index', filter: 'current_user'

    resources :batch_objects, only: :show do
      resources :batch_object_datastreams, only: :index
      resources :batch_object_relationships, only: :index
    end

    resources :export_files, only: %i[index new create]

    resources :file_uploads, only: %i[new create show]

    resources :ingest_folders, only: %i[new create show] do
      member do
        get 'procezz'
      end
    end

    resources :metadata_files, only: %i[new create show] do
      member do
        get 'procezz'
      end
    end

    resources :manifest_based_ingests, only: %i[new create show]

    resources :nested_folder_ingests, only: %i[new create show]

    resources :standard_ingests, only: %i[new create show]

    # Downloads
    get 'download/:id(/:ddr_file_type)' => 'downloads#show', :constraints => { id: id_constraint }, as: 'download'

    get 'roles/batch',   to: 'roles#batch'
    patch 'roles/batch', to: 'roles#batch'
  end
end

app/models/ddr/admin/admin_set_ability_definitions.rb
module Ddr::Admin
  #
  # Ported from ddr-core v1.16.0, with changes.
  #
  class AdminSetAbilityDefinitions < Ddr::Auth::AbilityDefinitions
    def call
      can :export, Ddr::AdminSet if curator?
    end
  end
end

app/models/ddr/admin/alias_ability_definitions.rb
module Ddr::Admin
  class AliasAbilityDefinitions < Ddr::Auth::AbilityDefinitions
    def call
      alias_action :attachments,
                   :captions,
                   :collection_info,
                   :components,
                   :event,
                   :events,
                   :files,
                   :iiif,
                   :intermediate,
                   :items,
                   :stream,
                   :structural_metadata,
                   :targets,
                   to: :read

      alias_action :roles, to: :grant

      alias_action :admin_metadata,
                   :generate_iiif,
                   :generate_structure,
                   to: :update

      alias_action :preview, to: :publish if Ddr::Admin.publication_preview_enabled
    end
  end
end

app/models/ddr/admin/batch_ability_definitions.rb
module Ddr::Admin
  class BatchAbilityDefinitions < Ddr::Auth::AbilityDefinitions
    def call
      can :read, [Ddr::Batch::Batch, Ddr::Batch::BatchObject] if authenticated?
      can(:manage, Ddr::Batch::Batch, user:)
      can :manage, Ddr::Batch::BatchObject do |batch_object|
        batch_object.batch.user == user
      end
    end
  end
end

app/models/ddr/admin/collection_ability_definitions.rb
module Ddr::Admin
  #
  # Ported from ddr-core, with changes.
  #
  class CollectionAbilityDefinitions < Ddr::Auth::AbilityDefinitions
    def call
      can :create, Ddr::Collection if curator?

      can :export, Ddr::Collection do |obj|
        has_policy_permission?(obj, Ddr::Auth::Permissions::READ)
      end
    end

    private

    def policy_permissions(obj)
      obj.policy_roles
         .select { |r| agents.include?(r.agent) }
         .map(&:permissions).flatten.uniq
    end

    def has_policy_permission?(obj, perm)
      policy_permissions(obj).include?(perm)
    end
  end
end

app/models/ddr/admin/event_ability_definitions.rb
module Ddr::Admin
  class EventAbilityDefinitions < Ddr::Auth::AbilityDefinitions
    def call
      can :read, Ddr::Events::Event do |event|
        can? :read, event.resource_id
      end
    end
  end
end

app/models/ddr/admin/ingest_folder_ability_definitions.rb
module Ddr::Admin
  class IngestFolderAbilityDefinitions < Ddr::Auth::AbilityDefinitions
    def call
      can :create, Ddr::IngestFolder do |ingest_folder|
        ingest_folder.collection_id? && can?(:add_children, ingest_folder.collection)
      end

      can %i[show procezz], Ddr::IngestFolder, user:
    end
  end
end

app/models/ddr/admin/manifest_based_ingest_ability_definitions.rb
module Ddr::Admin
  class ManifestBasedIngestAbilityDefinitions < Ddr::Auth::AbilityDefinitions
    def call
      can :create, Ddr::ManifestBasedIngest if can?(:create, Ddr::Collection)
      can :show, Ddr::ManifestBasedIngest, user:
    end
  end
end

app/models/ddr/admin/metadata_file_ability_definitions.rb
module Ddr::Admin
  class MetadataFileAbilityDefinitions < Ddr::Auth::AbilityDefinitions
    def call
      can :create, Ddr::MetadataFile if curator?

      return unless authenticated?

      can %i[show procezz], Ddr::MetadataFile, user_id: user.id
    end
  end
end

app/models/ddr/admin/nested_folder_ingest_ability_definitions.rb
module Ddr::Admin
  class NestedFolderIngestAbilityDefinitions < Ddr::Auth::AbilityDefinitions
    def call
      can :create, Ddr::NestedFolderIngest if can?(:create, Ddr::Collection)
      can :show, Ddr::NestedFolderIngest, user:
    end
  end
end

app/models/ddr/admin/standard_ingest_ability_definitions.rb
module Ddr::Admin
  class StandardIngestAbilityDefinitions < Ddr::Auth::AbilityDefinitions
    def call
      can :create, Ddr::StandardIngest if can?(:create, Ddr::Collection)
      can :show, Ddr::StandardIngest, user:
    end
  end
end

app/models/ddr/admin_set.rb
module Ddr
  AdminSet = Struct.new(:code, :title, keyword_init: true) do
    def self.config
      @config ||= YAML.load_file(::File.expand_path('../../../config/aux/admin_set.yml', __dir__))
    end

    def self.keystore
      @keystore ||= config.map { |entry| [entry['code'], new(entry).freeze] }.to_h.freeze
    end

    def self.all
      keystore.values
    end

    def self.call(obj)
      find_by_code(obj.admin_set)
    end

    def self.find_by_code(code)
      return unless code

      keystore.fetch(code)
    rescue KeyError => _e
      raise Ddr::NotFoundError, "AdminSet code '#{code}' not found."
    end

    def self.keys
      keystore.keys
    end

    def to_s
      title
    end
  end
end

app/models/ddr/attachment.rb
module Ddr
  class Attachment < Resource
    include V3::Unpublishable
    include HasContent
    include HasExtractedText

    attribute :attached_to_id, Valkyrie::Types::ID.optional

    # @return [Ddr::Collection] the collection to which this attachment is attached
    # @raise [Valkyrie::Persistence::ObjectNotFoundError] if the collection cannot be found
    def attached_to
      Ddr.query_service.find_by(id: attached_to_id) if attached_to_id
    end
  end
end

app/models/ddr/batch.rb
module Ddr
  module Batch
    class Error < ::StandardError; end

    # Error processing batch object
    class BatchObjectProcessingError < Error; end

    # Logging level for batch processing - defaults to Logger::INFO
    mattr_accessor :processor_logging_level do
      Logger::INFO
    end

    def self.table_name_prefix; end
  end
end

app/models/ddr/batch/batch.rb
module Ddr::Batch
  class Batch < ::ApplicationRecord
    belongs_to :user, inverse_of: :batches, class_name: '::User'
    has_many :batch_objects, -> { order('id ASC') }, inverse_of: :batch, dependent: :destroy

    OUTCOME_SUCCESS = 'SUCCESS'
    OUTCOME_FAILURE = 'FAILURE'
    OUTCOMES = [OUTCOME_SUCCESS, OUTCOME_FAILURE].freeze

    STATUS_READY = 'READY'
    STATUS_VALIDATING = 'VALIDATING'
    STATUS_INVALID = 'INVALID'
    STATUS_VALIDATED = 'VALIDATED'
    STATUS_QUEUED = 'QUEUED'
    STATUS_PROCESSING = 'PROCESSING'
    STATUS_RUNNING = 'RUNNING'
    STATUS_FINISHED = 'FINISHED'
    STATUS_INTERRUPTED = 'INTERRUPTED'
    STATUS_RESTARTABLE = 'INTERRUPTED - RESTARTABLE'
    STATUS_QUEUED_FOR_DELETION = 'QUEUED FOR DELETION'
    STATUS_DELETING = 'DELETING'

    STATUS_VALUES = [
      STATUS_READY,
      STATUS_VALIDATING,
      STATUS_INVALID,
      STATUS_VALIDATED,
      STATUS_QUEUED,
      STATUS_PROCESSING,
      STATUS_RUNNING,
      STATUS_FINISHED,
      STATUS_INTERRUPTED,
      STATUS_RESTARTABLE,
      STATUS_QUEUED_FOR_DELETION,
      STATUS_DELETING
    ].freeze

    def handled_count
      batch_objects.where(handled: true).count
    end

    def success_count
      batch_objects.where(verified: true).count
    end

    def time_to_complete
      return if start.nil?
      return unless handled_count > 0

      handled = handled_count
      ((Time.now - start.to_time) / handled) * (batch_objects.count - handled)
    end

    def found_resource_ids
      @found_resource_ids ||= {}
    end

    def add_found_resource_id(resource_id, model)
      @found_resource_ids[resource_id] = model
    end

    def pre_assigned_resource_ids
      @pre_assigned_resource_ids ||= collect_pre_assigned_resource_ids
    end

    def collect_pre_assigned_resource_ids
      batch_objects.map { |x| x.resource_id.presence }.compact
    end

    def unhandled_objects?
      batch_objects.any? { |batch_object| !batch_object.handled? }
    end

    def finished?
      status == STATUS_FINISHED
    end

    def deletable?
      [nil,
       Ddr::Batch::Batch::STATUS_READY,
       Ddr::Batch::Batch::STATUS_VALIDATED,
       Ddr::Batch::Batch::STATUS_INVALID].include?(status)
    end

    # Used in reprocessing failed batches, reset 'handled' to false for failed batch objects
    def reset!
      batch_objects.where(verified: 'f', handled: 't').in_batches do |objects|
        objects.update_all(handled: 'f')
      end
    end
  end
end

app/models/ddr/batch/batch_messages.rb
require 'csv'

module Ddr
  module Batch
    class BatchMessages
      attr_reader :batch, :filters

      def initialize(batch, filters: {})
        @batch = batch
        @filters = filters.dup
      end

      # The message records
      # @return [ActiveRecord::Relation]
      def records
        BatchObjectMessage
          .joins(:batch_object)
          .where(batch_objects: filters.merge(batch_id: batch.id))
          .order(:created_at)
      end

      # CSV headers
      # @return [Array<String>]
      def headers
        BatchObjectMessage.attribute_names
      end

      # CSV output
      # @return [String]
      def to_csv
        CSV.generate do |csv|
          csv << headers

          records.each do |record|
            csv << record.serializable_hash.values_at(*headers)
          end
        end
      end
    end
  end
end

app/models/ddr/batch/batch_object_attribute.rb
module Ddr::Batch
  class BatchObjectAttribute < ::ApplicationRecord
    belongs_to :batch_object, inverse_of: :batch_object_attributes

    OPERATION_ADD = 'ADD'              # Add the provided value to the attribute
    OPERATION_DELETE = 'DELETE'        # Delete the provided value from the attribute
    OPERATION_CLEAR = 'CLEAR'          # Clear all values from the attribute

    OPERATIONS = [OPERATION_ADD, OPERATION_DELETE, OPERATION_CLEAR].freeze

    VALUE_TYPE_STRING = 'STRING'

    VALUE_TYPES = [VALUE_TYPE_STRING].freeze

    validates :operation, inclusion: { in: OPERATIONS }
    with_options if: :operation_requires_name? do
      validates :name, presence: true
    end
    validate :valid_attribute_name, if: proc { batch_object.model && name }
    with_options if: :operation_requires_value? do
      validates :value, presence: true
      validates :value_type, inclusion: { in: VALUE_TYPES }
    end

    def operation_requires_name?
      [OPERATION_ADD, OPERATION_DELETE, OPERATION_CLEAR].include? operation
    end

    def operation_requires_value?
      [OPERATION_ADD, OPERATION_DELETE].include? operation
    end

    def valid_attribute_name
      errors.add(:name, 'is not valid') unless attribute_name_valid?
    end

    def attribute_name_valid?
      (Ddr::Describable.term_names + Ddr::HasAdminMetadata.term_names).include? name.to_sym
    end
  end
end

app/models/ddr/batch/batch_object_datastream.rb
module Ddr::Batch
  class BatchObjectDatastream < ::ApplicationRecord
    belongs_to :batch_object, inverse_of: :batch_object_datastreams

    OPERATION_ADD = 'ADD' # add this datastream to the object -- considered an error if datastream already exists
    OPERATION_ADDUPDATE = 'ADDUPDATE' # add this datastream to or update this datastream in the object
    OPERATION_UPDATE = 'UPDATE' # update this datastream in the object -- considered an error if datastream does not already exist
    OPERATION_DELETE = 'DELETE' # delete this datastream from the object -- considered an error if datastream does not exist

    OPERATIONS = [OPERATION_ADD, OPERATION_ADDUPDATE, OPERATION_UPDATE, OPERATION_DELETE].freeze

    PAYLOAD_TYPE_BYTES = 'BYTES'
    PAYLOAD_TYPE_FILENAME = 'FILENAME'

    PAYLOAD_TYPES = [PAYLOAD_TYPE_BYTES, PAYLOAD_TYPE_FILENAME].freeze
  end
end

app/models/ddr/batch/batch_object_message.rb
module Ddr::Batch
  class BatchObjectMessage < ::ApplicationRecord
    belongs_to :batch_object, inverse_of: :batch_object_messages

    validates :message, presence: true
  end
end

app/models/ddr/batch/batch_object_relationship.rb
module Ddr::Batch
  class BatchObjectRelationship < ::ApplicationRecord
    belongs_to :batch_object, inverse_of: :batch_object_relationships

    RELATIONSHIP_ADMIN_POLICY = 'admin_policy'
    RELATIONSHIP_FOR_COLLECTION = 'for_collection'
    RELATIONSHIP_PARENT = 'parent'
    RELATIONSHIP_ITEM = 'item'
    RELATIONSHIP_COMPONENT = 'component'
    RELATIONSHIP_ATTACHED_TO = 'attached_to'

    RELATIONSHIPS = [RELATIONSHIP_ADMIN_POLICY, RELATIONSHIP_FOR_COLLECTION, RELATIONSHIP_PARENT, RELATIONSHIP_ITEM,
                     RELATIONSHIP_COMPONENT, RELATIONSHIP_ATTACHED_TO].freeze

    OPERATION_ADD = 'ADD'
    OPERATION_UPDATE = 'UPDATE'
    OPERATION_DELETE = 'DELETE'
    OPERATIONS = [OPERATION_ADD, OPERATION_UPDATE, OPERATION_DELETE].freeze

    OBJECT_TYPE_ID = 'ID'

    # Legacy note: There are also records having object_type = 'PID'
    OBJECT_TYPES = [OBJECT_TYPE_ID]
  end
end

app/views/ddr/ingest_folders/new.html.erb
<h1>DPC Folder Ingest</h1>

<div class="row">
  <div class="col-md-5">
    <% if @ingest_folder.errors.any? %>
      <div class="alert alert-danger">
        <strong><%= pluralize(@ingest_folder.errors.count, "error") %>
          prohibited this ingest folder from being scanned:</strong>
        <ul>
          <% @ingest_folder.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_for @ingest_folder, html: { autocomplete: 'off' } do |f| %>
      <div class="form-group">
        <%= f.label I18n.t('ddr.ingest_folder.labels.collection_id') %>
        <%= f.hidden_field :collection_id %>
        <%= object_display_title(@ingest_folder.collection_id) %>
      </div>
      <div class="form-group">
        <%= f.label t('ddr.ingest_folder.labels.base_path') %>
        <%= f.select :base_path, options_for_select(permitted_ingest_folder_bases), {}, {class: 'form-control'} %>
      </div>
      <div class="form-group">
        <%= f.label t('ddr.ingest_folder.labels.sub_path') %>
        <%= f.text_field :sub_path, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label t('ddr.ingest_folder.labels.checksum_file') %>
        <%= f.text_field :checksum_file, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label t('ddr.ingest_folder.labels.checksum_type') %>
        <%= f.select :checksum_type,
                     options_for_select(checksum_type_options_for_select,
                                        @ingest_folder.checksum_type || Ddr::IngestFolder.default_checksum_type),
                     class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label t('ddr.ingest_folder.labels.parent_id_length') %>
        <%= f.text_field :parent_id_length, class: 'form-control' %>
        <span class="form-text"><%= t('ddr.ingest_folder.help.parent_id_length')%></span>
      </div>
      <div class="form-group">
        <%= f.submit t('ddr.ingest_folder.scan_folder'), id: 'ingest_folders_submit_button', class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/ddr/ingest_folders/queued.html.erb
<h1>DPC Folder Ingest</h1>

<p class="lead">
  <%= t('ddr.ingest_folder.queued', email: @ingest_folder.user.email) %>
</p>

<div class="alert alert-warning">
  <%= t('ddr.ingest_folder.reload_warning_html') %>
</div>

<div class="row">
  <div class="col-md-2">
    Collection:
  </div>
  <div class="col-md-4">
    <%= object_display_title(@ingest_folder.collection_id) %>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    Folder Path:
  </div>
  <div class="col-md-4">
    <%= @ingest_folder.abbreviated_path %>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    User:
  </div>
  <div class="col-md-4">
    <%= @ingest_folder.user.user_key %>
  </div>
</div>

app/views/ddr/ingest_folders/show.html.erb
<h1>DPC Folder Ingest</h1>

<% if @ingest_folder.errors.any? %>
  <div class="alert alert-danger">
    <h2><%= pluralize(@ingest_folder.errors.count, "warning") %> for this ingest folder:</h2>

    <ul>
      <% @ingest_folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= content_tag(:table, :class => 'table-bordered') do %>

  <%= content_tag(:tr) do %>
    <%= content_tag(:td, I18n.t('ddr.ingest_folder.labels.collection_id')) %>
    <%= content_tag(:td, object_display_title(@ingest_folder.collection_id)) %>
  <% end %>
  <%= content_tag(:tr) do %>
    <%= content_tag(:td, I18n.t('ddr.ingest_folder.labels.folder')) %>
    <%= content_tag(:td, @ingest_folder.abbreviated_path) %>
  <% end %>
  <%= content_tag(:tr) do %>
    <%= content_tag(:td, I18n.t('ddr.ingest_folder.labels.total_files_scanned')) %>
    <%= content_tag(:td, @scan_results.total_count) %>
  <% end %>
  <%= content_tag(:tr) do %>
    <%= content_tag(:td, I18n.t('ddr.ingest_folder.labels.objects_to_ingest')) %>
    <%= content_tag(:td) do %>
      <%= content_tag(:ul) do %>
        <%= content_tag(:li, file_count) %>
        <%= content_tag(:li, parent_count) %>
        <%= content_tag(:li, target_count) %>
      <% end %>
    <% end %>
  <% end %>
  <%= content_tag(:tr) do %>
    <%= content_tag(:td, I18n.t('ddr.ingest_folder.labels.excluded_files')) %>
    <%= content_tag(:td) do %>
      <%= content_tag(:ul) do %>
        <%= excluded_file_list %>
      <% end %>
    <% end %>
  <% end %>
  <%= content_tag(:tr) do %>
    <%= content_tag(:td, I18n.t('ddr.ingest_folder.labels.checksum_file')) %>
    <%= content_tag(:td, @ingest_folder.checksum_file) %>
  <% end %>
  <% if @ingest_folder.checksum_file.present? %>
    <%= content_tag(:tr) do %>
      <%= content_tag(:td, I18n.t('ddr.ingest_folder.labels.checksum_type')) %>
      <%= content_tag(:td, @ingest_folder.checksum_type) %>
    <% end %>
  <% end %>
  <%= content_tag(:tr) do %>
    <%= content_tag(:td, I18n.t('ddr.ingest_folder.labels.parent_id_length')) %>
    <%= content_tag(:td, @ingest_folder.parent_id_length) %>
  <% end %>

<% end %>

<div class="form-group">
  <%= link_to I18n.t('ddr.ingest_folder.create_batch'), procezz_ddr_ingest_folder_path(@ingest_folder), class: "btn btn-primary", id: "ingest_folder_create_batch_btn" %>
</div>